#!/bin/bash
set -e
sudo -Sy
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

echo "INSTALADOR DE HYPRLAND PERSONALIZADO"
sudo pacman -S --needed hyprland waybar foot rofi grim slurp wl-clipboard cliphist mako pamixer brightnessctl thunar xdg-desktop-portal-hyprland blueman awww
if command -v paru &>/dev/null; then
    $AUR_HELPER="paru"
elif command -v yay &>/dev/null; then
    $AUR_HELPER="yay"
else
    echo "ERROR: NECESITAS INSTALAR PARU O YAY"
fi
$AUR_HELPER -S hyprmod

echo "PAQUETES INSTALADOS, AHORA SE INSTALARÁN LAS CONFIGURACIONES"

cp -r "$SCRIPT_DIR/hypr" ~/.config
echo "Hyperland configurado"

cp -r "$SCRIPT_DIR/rofi" ~/.config
echo "Rofi configurado"

cp -r "$SCRIPT_DIR/waybar" ~/.config
echo "Waybar configurado"

echo "INSTALACIÓN Y CONFIGURACIÓN TERMINADA"